version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo-healthcare
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - healthcare-network

  migration:
    build: .
    container_name: migration-healthcare
    depends_on:
      - mongo
    environment:
      CSV_PATH: /data/healthcare_dataset.csv
      MONGO_MODE: docker
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: healthcare
      MONGO_COLLECTION_NAME: patients
    volumes:
      - ../Data:/data:ro
    command: ["uv", "run", "main.py"]
    networks:
      - healthcare-network

volumes:
  mongo_data:

networks:
  healthcare-network:
    driver: bridge